# Development environment configuration
---
spring:
  h2:
    console.enabled: true
  jpa:
    show_sql: true
logging:
  level:
    root: info
    org:
      springframework: info
      hibernate: warn

      
    
